/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as ApiPublicBadgeIdRouteImport } from './routes/api/public/badge.$id'
import { Route as ApiPublicShareImageIdRouteImport } from './routes/api/public/share-image.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBadgeIdRoute = ApiPublicBadgeIdRouteImport.update({
  id: '/api/public/badge/$id',
  path: '/api/public/badge/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareImageIdRoute = ApiPublicShareImageIdRouteImport.update({
  id: '/api/public/share-image/$id',
  path: '/api/public/share-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/directory': typeof DirectoryRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/badge/$id': typeof ApiPublicBadgeIdRoute
  '/api/public/share-image/$id': typeof ApiPublicShareImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/directory': typeof DirectoryRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/badge/$id': typeof ApiPublicBadgeIdRoute
  '/api/public/share-image/$id': typeof ApiPublicShareImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/community': typeof CommunityRoute
  '/directory': typeof DirectoryRoute
  '/history': typeof HistoryRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy': typeof PrivacyRoute
  '/quiz': typeof QuizRoute
  '/referral': typeof ReferralRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/report/$id': typeof ReportIdRoute
  '/api/public/badge/$id': typeof ApiPublicBadgeIdRoute
  '/api/public/share-image/$id': typeof ApiPublicShareImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/community'
    | '/directory'
    | '/history'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/referral'
    | '/support'
    | '/terms'
    | '/report/$id'
    | '/api/public/badge/$id'
    | '/api/public/share-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/community'
    | '/directory'
    | '/history'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/referral'
    | '/support'
    | '/terms'
    | '/report/$id'
    | '/api/public/badge/$id'
    | '/api/public/share-image/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/community'
    | '/directory'
    | '/history'
    | '/how-it-works'
    | '/privacy'
    | '/quiz'
    | '/referral'
    | '/support'
    | '/terms'
    | '/report/$id'
    | '/api/public/badge/$id'
    | '/api/public/share-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  CommunityRoute: typeof CommunityRoute
  DirectoryRoute: typeof DirectoryRoute
  HistoryRoute: typeof HistoryRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyRoute: typeof PrivacyRoute
  QuizRoute: typeof QuizRoute
  ReferralRoute: typeof ReferralRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ReportIdRoute: typeof ReportIdRoute
  ApiPublicBadgeIdRoute: typeof ApiPublicBadgeIdRoute
  ApiPublicShareImageIdRoute: typeof ApiPublicShareImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/badge/$id': {
      id: '/api/public/badge/$id'
      path: '/api/public/badge/$id'
      fullPath: '/api/public/badge/$id'
      preLoaderRoute: typeof ApiPublicBadgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share-image/$id': {
      id: '/api/public/share-image/$id'
      path: '/api/public/share-image/$id'
      fullPath: '/api/public/share-image/$id'
      preLoaderRoute: typeof ApiPublicShareImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  CommunityRoute: CommunityRoute,
  DirectoryRoute: DirectoryRoute,
  HistoryRoute: HistoryRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyRoute: PrivacyRoute,
  QuizRoute: QuizRoute,
  ReferralRoute: ReferralRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ReportIdRoute: ReportIdRoute,
  ApiPublicBadgeIdRoute: ApiPublicBadgeIdRoute,
  ApiPublicShareImageIdRoute: ApiPublicShareImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
